### PR TITLE
Ability to add DataDog tags to stats

### PR DESCRIPTION
**Pull request by fredrikelinder**

### CODE REVIEW

**Comment by lpgauth** [comment]
Hi, this is a big patch... and I'm on vacation right now, but once I'm back @ work I'll have a look and get back to you.

Thanks

**Comment by fredrikelinder** [comment]
Thank you

Would an update where the msg being sent to the udp port directly, instead of going through the statdserl process be ok with you?

Achieved by storing the udp port in a protected ets table?

**Comment by lpgauth** [comment]
That's a good idea, not sure why I never thought of that :+1:

**Comment by n-clark** [comment]
Is this still on the docket? It would be very helpful to have this merged in!

**Comment by lpgauth** [comment]
Opened https://github.com/lpgauth/statsderl/issues/17 and added to my todo.

**Pull request closed without merging**
